Repository DeveloperAcademy-POSTECH/2024-NC2-M10-WeatherKit, pull requests merged in 2024-06, with the labels that each got.

#2 [FEAT] WeatherKit 연결
  capuri-sun.xcodeproj/project.pbxproj
  capuri-sun.xcodeproj/project.xcworkspace/xcuserdata/choseyeon.xcuserdatad/UserInterfaceState.xcuserstate
  capuri-sun/WeatherView.swift
  capuri-sun/capuri_sunApp.swift
Labels: FEAT, 카야

#8 [FEAT] 알람 뷰 구현 / UI 구현
  capuri-sun.xcodeproj/project.pbxproj
  capuri-sun.xcodeproj/project.xcworkspace/xcuserdata/harim.xcuserdatad/UserInterfaceState.xcuserstate
  capuri-sun.xcodeproj/xcuserdata/harim.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  capuri-sun.xcodeproj/xcuserdata/harim.xcuserdatad/xcschemes/xcschememanagement.plist
  capuri-sun/Assets.xcassets/alarmbutton.colorset/Contents.json
  capuri-sun/Assets.xcassets/alarmcolor.colorset/Contents.json
  capuri-sun/Assets.xcassets/alarmcolor2.colorset/Contents.json
  capuri-sun/Assets.xcassets/alarmcolor3.colorset/Contents.json
  capuri-sun/Assets.xcassets/alarmcolor4.colorset/Contents.json
  capuri-sun/Assets.xcassets/alarmcolor5.colorset/Contents.json
  capuri-sun/Assets.xcassets/img_AlarmBackground.imageset/(처음)알림주기설정.png
  capuri-sun/Assets.xcassets/img_AlarmBackground.imageset/Contents.json
  capuri-sun/View/AlarmView.swift
  capuri-sun/View/Background2.png
Labels: FEAT, UI, 푸딩

#10 [FEAT] 온보딩 뷰 / 제스처 구현
  capuri-sun.xcodeproj/project.xcworkspace/xcuserdata/harim.xcuserdatad/UserInterfaceState.xcuserstate
  capuri-sun/View/Onboarding/OnboardingView.swift
Labels: FEAT, 푸딩

#13 [FEAT] 이슈 해결
  LiveActivity/LiveActivity.swift
  LiveActivity/LiveActivityLiveActivity.swift
  capuri-sun.xcodeproj/project.xcworkspace/xcuserdata/choseyeon.xcuserdatad/UserInterfaceState.xcuserstate
  capuri-sun.xcodeproj/xcshareddata/xcschemes/capuri-sun.xcscheme
  capuri-sun.xcodeproj/xcuserdata/choseyeon.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  capuri-sun.xcodeproj/xcuserdata/choseyeon.xcuserdatad/xcschemes/xcschememanagement.plist
  capuri-sun/View/AlarmTimeManager.swift
  capuri-sun/View/AlarmView.swift
  capuri-sun/View/Information/SuncreamView.swift
  capuri-sun/View/Main/MainView.swift
  capuri-sun/View/Onboarding/OnboardingView.swift
  capuri-sun/View/Onboarding/PukaSunView.swift
  capuri-sun/capuri_sunApp.swift
Labels: FEAT, 카야
